export const site = {
  name: "AI Label Remover",
  shortName: "AI Label Remover",
  url: "https://ailabelremover.theatom.lk",
  domain: "ailabelremover.theatom.lk",
  tagline: "Free, ad-free AI metadata cleaning for photos and videos — private in your browser.",
  description:
    "Free, ad-free AI label remover for photos and videos. Remove C2PA, XMP, EXIF, IPTC and video container metadata without a login or media upload. Lossless, private and browser-based.",
  publisher: "The Atom",
  publisherUrl: "https://theatom.lk",
  email: "hello@theatom.lk",
  feedbackEmail: "connect.theatom@gmail.com",
  locale: "en_US",
  keywords: [
    "ai label remover",
    "remove ai label",
    "remove ai info instagram",
    "made with ai label remover",
    "ai metadata cleaner",
    "ai metadata remover",
    "c2pa remover",
    "remove c2pa metadata",
    "xmp metadata remover",
    "exif remover online",
    "remove ai tag from photo",
    "instagram ai info remover",
    "tiktok ai generated label remover",
    "pinterest ai label remover",
    "strip metadata from image",
    "video ai label remover",
    "remove ai metadata from video",
    "video metadata remover",
    "remove c2pa from video",
    "mp4 metadata cleaner",
    "mov metadata remover",
    "free ai label remover no login",
    "ad free ai metadata remover",
    "private ai label remover",
    "browser based video metadata cleaner",
  ],
} as const;

export const MAX_FILE_MB = 15;
export const MAX_BATCH = 30;
